install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
language: erlang
script: ./rebar3 eunit
otp_release:
  - 21.2
  - 21.1
  - 21.0
  - 20.3
  - 20.2
  - 20.1
  - 20.0
  - 19.3
  - 19.2
  - 19.1
  - 19.0
